### ISSUE TITLE
Connection rest by peer: socket write error

### ISSUE THREAD

**Issue by HakShak** [JetBrains/teamcity-s3-artifact-storage-plugin#12]
We are consistently getting this error when artifact rules capture many files for upload:
`[Publishing artifacts] Failed to publish artifacts: Connection reset by peer: socket write error`

Is there any way to get more information from this error such as the file it was failing on?

**Comment by dtretyakov** [comment]
@HakShak, do you have Signed URL feature enabled in S3 storage profile?

**Comment by aquarhead** [comment]
@dtretyakov are you talking about this?

![image](https://user-images.githubusercontent.com/222272/37834911-d29b4d76-2ea6-11e8-83c8-3de68ea0ae48.png)

**Comment by dtretyakov** [comment]
@aquarhead, yes, I'm talking about this option. The possible reason was fixed in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCityTrunk&tab=buildTypeHistoryList&guest=1&branch_TeamCityPluginsByJetBrains_AwsS3ArtifactStorage=%3Cdefault%3E), so please update the plugin and let me know whether it reproduces again.

**Comment by dimyriy** [comment]
@HakShak, the issue has been moved to our tracker. Please let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60691.
