### ISSUE TITLE
HTML report artifact storage 403 forbidden

### ISSUE THREAD

**Issue by theangrydev** [JetBrains/teamcity-s3-artifact-storage-plugin#43]
I have some reports in my build artifacts that are spread across a number of HTML, CSS and JS files that use relative links to render the pages. 

This works fine without the s3 storage plugin, but when using the storage plugin, only the specific page requested is allowed and any included files fail with a 403.

Is there a way to make this work with the plugin?

**Comment by dimyriy** [comment]
You can use regular file upload instead of signed one and that would proxy artifacts through teamcity instead of redirecting to S3.
Also, you may utilize reports tabs, since they are specifically designed for that.
https://www.jetbrains.com/help/teamcity/including-third-party-reports-in-the-build-results.html
