### ISSUE TITLE
Pick Profile when using "Use default credential provider chain"

### ISSUE THREAD

**Issue by TechnicalMercenary** [JetBrains/teamcity-s3-artifact-storage-plugin#44]
We have many AWS accounts and Team City needs to push artifacts to several different accounts.

Our security is fairly stringent and I am only allowed to use the "Use default credential provider chain"

Is it possible?  It would be nice if I could specify the aws profile defined in the ~/.aws/credentials file like our security team wants.

**Comment by dimyriy** [comment]
That is unfortunately not possible since the default credentials just use what SDK provided on the machine. Meaning, mostly the credentials specified via environment variables.
Note also that the credentials for artefacts uploading should be placed on the agent machine itself, not on the TeamCity server machine.
